import { CrewProfile, Job } from '@/types';

export const mockCrew: CrewProfile[] = [
  {
    id: "c1",
    userId: "u1",
    fullName: "Elena Voss",
    position: "Chief Stewardess",
    yearsExperience: 14,
    certifications: ["STCW", "ENG1", "Yachtmaster Offshore", "Food Hygiene Level 3"],
    preferredYachtTypes: ["Motor Yacht", "Superyacht 50m+"],
    languages: ["English", "German", "French"],
    bio: "Highly experienced Chief Stewardess with a calm, service-oriented approach. Specialized in high-net-worth family rotations and wine service.",
    availability: "immediate",
    location: "Antibes",
    verified: true,
  },
  {
    id: "c2",
    userId: "u2",
    fullName: "Marcus Hale",
    position: "Second Engineer",
    yearsExperience: 9,
    certifications: ["STCW", "ENG1", "Yachtmaster", "High Voltage"],
    preferredYachtTypes: ["Motor Yacht", "Explorer Yacht"],
    languages: ["English", "Spanish"],
    bio: "Detail-oriented engineer with strong technical troubleshooting skills. Comfortable on both new builds and refits.",
    availability: "1-month",
    location: "Palma",
    verified: true,
  },
  {
    id: "c3",
    userId: "u3",
    fullName: "Sofia Ramirez",
    position: "Head of Interior",
    yearsExperience: 11,
    certifications: ["STCW", "ENG1", "Yachtmaster", "Silver Service"],
    preferredYachtTypes: ["Motor Yacht", "Sailing Yacht 40m+"],
    languages: ["English", "Spanish", "Italian"],
    bio: "Creative and highly organized HOD with excellent team leadership. Strong background in luxury service and guest relations.",
    availability: "immediate",
    location: "Barcelona",
    verified: true,
  },
];

export const mockJobs: Job[] = [
  {
    id: "j1",
    employerId: "e1",
    title: "Chief Stewardess",
    position: "Chief Stewardess",
    yachtType: "Motor Yacht 55m",
    location: "Mediterranean (Summer)",
    startDate: "2026-05-01",
    duration: "6 months",
    salaryRange: "€6,500 - €7,500",
    requirements: ["STCW", "Minimum 10 years experience", "Previous 50m+ experience"],
    description: "Looking for an exceptional Chief Stewardess for a busy family yacht. Must be calm under pressure and excellent with children.",
    status: "open",
    createdAt: "2026-04-10",
  },
  {
    id: "j2",
    employerId: "e2",
    title: "Second Engineer",
    position: "Second Engineer",
    yachtType: "Explorer Yacht 48m",
    location: "Caribbean & Pacific",
    startDate: "2026-06-15",
    duration: "12 months",
    salaryRange: "€5,000 - €5,800",
    requirements: ["STCW", "ENG1", "Previous engineer experience on 40m+"],
    description: "We need a reliable and technically strong Second Engineer for an ambitious world-cruising program.",
    status: "open",
    createdAt: "2026-04-12",
  },
  {
    id: "j3",
    employerId: "e3",
    title: "Head of Interior",
    position: "Head of Interior",
    yachtType: "Motor Yacht 42m",
    location: "South of France",
    startDate: "2026-05-20",
    duration: "5 months",
    salaryRange: "€5,200 - €6,000",
    requirements: ["STCW", "Strong leadership experience", "Silver service trained"],
    description: "Beautiful privately owned yacht seeking an organized and warm Head of Interior for the summer season.",
    status: "open",
    createdAt: "2026-04-15",
  },
];
