import { CrewProfile, Job } from '@/types';

export const mockCrew: CrewProfile[] = [
  {
    id: "c1",
    userId: "u1",
    fullName: "Elena Voss",
    position: "Chief Stewardess",
    yearsExperience: 14,
    certifications: ["STCW", "ENG1", "Yachtmaster Offshore", "Food Hygiene Level 3"],
    preferredYachtTypes: ["Motor Yacht", "Superyacht 50m+"],
    languages: ["English", "German", "French"],
    bio: "Highly experienced Chief Stewardess with a calm, service-oriented approach. Specialized in high-net-worth family rotations and wine service.",
    availability: "immediate",
    location: "Antibes",
    verified: true,
  },
  {
    id: "c2",
    userId: "u2",
    fullName: "Marcus Hale",
    position: "Second Engineer",
    yearsExperience: 9,
    certifications: ["STCW", "ENG1", "Yachtmaster", "High Voltage"],
    preferredYachtTypes: ["Motor Yacht", "Explorer Yacht"],
    languages: ["English", "Spanish"],
    bio: "Detail-oriented engineer with strong technical troubleshooting skills. Comfortable on both new builds and refits.",
    availability: "1-month",
    location: "Palma",
    verified: true,
  },
  {
    id: "c3",
    userId: "u3",
    fullName: "Sofia Ramirez",
    position: "Head of Interior",
    yearsExperience: 11,
    certifications: ["STCW", "ENG1", "Yachtmaster", "Silver Service"],
    preferredYachtTypes: ["Motor Yacht", "Sailing Yacht 40m+"],
    languages: ["English", "Spanish", "Italian"],
    bio: "Creative and highly organized HOD with excellent team leadership. Strong background in luxury service and guest relations.",
    availability: "immediate",
    location: "Barcelona",
    verified: true,
  },
  {
    id: "c4",
    userId: "u4",
    fullName: "Liam Carter",
    position: "Deckhand",
    yearsExperience: 6,
    certifications: ["STCW", "Powerboat Level 2", "Tender Driving", "Diving PADI"],
    preferredYachtTypes: ["Motor Yacht", "Explorer Yacht"],
    languages: ["English", "Spanish"],
    bio: "Energetic and meticulous Deckhand with a passion for watersports and guest experiences. Expert in tender operations, diving excursions, and maintaining pristine exteriors on high-profile yachts.",
    availability: "immediate",
    location: "Palma",
    verified: true,
    photoUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80",
  },
  {
    id: "c5",
    userId: "u5",
    fullName: "Viktor Lang",
    position: "Chief Engineer",
    yearsExperience: 17,
    certifications: ["STCW", "ENG1", "High Voltage", "Yachtmaster Ocean", "Marine Engineering"],
    preferredYachtTypes: ["Motor Yacht 50m+", "Explorer Yacht"],
    languages: ["English", "German", "Dutch"],
    bio: "World-class Chief Engineer with an impeccable record on 60m+ vessels. Known for calm crisis leadership during complex refits and transatlantic crossings. Deep expertise in hybrid propulsion and zero-emission systems.",
    availability: "1-month",
    location: "Hamburg",
    verified: true,
    photoUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&q=80",
  },
  {
    id: "c6",
    userId: "u6",
    fullName: "Isabella Moreau",
    position: "Second Stewardess",
    yearsExperience: 8,
    certifications: ["STCW", "Silver Service", "Wine & Spirits", "First Aid"],
    preferredYachtTypes: ["Motor Yacht", "Sailing Yacht 40m+"],
    languages: ["English", "French", "Italian"],
    bio: "Polished Second Stewardess with an intuitive sense of service and an eye for detail. Excelled in private family yachts and charter seasons alike. Brings warmth, discretion, and flawless table service.",
    availability: "immediate",
    location: "Antibes",
    verified: true,
    photoUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80",
  },
  {
    id: "c7",
    userId: "u7",
    fullName: "Rafael Santos",
    position: "Bosun",
    yearsExperience: 13,
    certifications: ["STCW", "Yachtmaster", "RYA Powerboat", "Crane & Rigging", "Diving"],
    preferredYachtTypes: ["Motor Yacht 50m+", "Explorer Yacht"],
    languages: ["English", "Portuguese", "Spanish"],
    bio: "Commanding yet approachable Bosun with exceptional leadership of deck teams. Master of complex anchoring, superyacht tenders, and watersports programs. Trusted by captains for his precision and crew mentorship.",
    availability: "immediate",
    location: "Palma",
    verified: true,
    photoUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&q=80",
  },
];

export const mockJobs: Job[] = [
  {
    id: "j1",
    employerId: "e1",
    title: "Chief Stewardess",
    position: "Chief Stewardess",
    yachtType: "Motor Yacht 55m",
    location: "Mediterranean (Summer)",
    startDate: "2026-05-01",
    duration: "6 months",
    salaryRange: "€6,500 - €7,500",
    requirements: ["STCW", "Minimum 10 years experience", "Previous 50m+ experience"],
    description: "Looking for an exceptional Chief Stewardess for a busy family yacht. Must be calm under pressure and excellent with children.",
    status: "open",
    createdAt: "2026-04-10",
  },
  {
    id: "j2",
    employerId: "e2",
    title: "Second Engineer",
    position: "Second Engineer",
    yachtType: "Explorer Yacht 48m",
    location: "Caribbean & Pacific",
    startDate: "2026-06-15",
    duration: "12 months",
    salaryRange: "€5,000 - €5,800",
    requirements: ["STCW", "ENG1", "Previous engineer experience on 40m+"],
    description: "We need a reliable and technically strong Second Engineer for an ambitious world-cruising program.",
    status: "open",
    createdAt: "2026-04-12",
  },
  {
    id: "j3",
    employerId: "e3",
    title: "Head of Interior",
    position: "Head of Interior",
    yachtType: "Motor Yacht 42m",
    location: "South of France",
    startDate: "2026-05-20",
    duration: "5 months",
    salaryRange: "€5,200 - €6,000",
    requirements: ["STCW", "Strong leadership experience", "Silver service trained"],
    description: "Beautiful privately owned yacht seeking an organized and warm Head of Interior for the summer season.",
    status: "open",
    createdAt: "2026-04-15",
  },
];
